environment: production
chdir: /home/igor/ruby/small-blog/
address: 127.0.0.1
user: root
group: root
port: 5000
pid: /home/igor/ruby/small-blog/thin.pid
rackup: /home/igor/ruby/small-blog/config/rackup.ru
log: /home/igor/ruby/small-blog/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true